### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by cjsewell** [rdennis/cassette.mapfile#2]
Is it possible for you to update the [ Nuget Cassette.MapFile package](http://www.nuget.org/packages/Cassette.MapFile/) to incorporate the support for CSS map files changes?

Cheers!

**Comment by rdennis** [comment]
Done https://www.nuget.org/packages/Cassette.MapFile/

**Comment by cjsewell** [comment]
Excellent. Thanks for that. Updated and its working good!
